%YAML 1.2
---

vgg_cfgs:
  -
    in_channels: 1
    block_cfg: [64, 'M']
    output_size: 12544
  -
    in_channels: 64
    block_cfg: [128, 'M']
    output_size: 6272
  -
    in_channels: 128
    block_cfg: [256, 256, 'M']
    output_size: 2304