phy_array_readMode: 2
phy_array_writeMode: 0
writeV: 3
readV: 1
computeV: 1
# C2C variation, r = Rtarget * exp(q);  q ~ N(0, theta)   
C2C_en: 
    enable: false
    theta: 0.1
D2D_en: false
# I = k*sinh(a*v)
nonLinearIV_en: false
write_cnt_en: false
latency_cal:  #all latency is xx ns 
    enable: false
    parMMPhyNum: 256
    parWrPhyNum:  -1
    parPhyWrSize: 64
    phyWrLatency: 2000
    phyMMLatency: 100
    phyReLatency: 80
    addLatency: 5
    addTreeWideSize: 128
    addTreeSharedNum: 8

energy_cal:  #all energy is J
    enable: false
    readRowPeripheryEnergy: 0
    readColPeripheryEnergy: 0
    readUseProbability: false #use probability to calculate or not
    writeRowPeripheryEnergy: 0
    writeColPeripheryEnergy: 0
    writeParallelism: 8 #now we don't support it
    writeUseProbability: true
    DACEnergy: 0
    ADCEnergy: 0
    computeRowPeripheryEnergy: 0
    computeColPeripheryEnergy: 0
    adderEnergy: 0  #add vertical out
    computeUseProbability: false
    CellPD: #read probability distribution, if not illegal, exit
      - 0.1
      - 0.86
      - 0.03
      - 0.01
    CellPDDefault: 0 #0:equal probabilty 1:100% max value
    inVPD: #read probability distribution, if not illegal, exit
      - 0.23
      - 0.24
      - 0.28
      - 0.25
    inVPDDefault: 0 #0:equal probabilty 1:100% max value
    
ir_drop:
    enable: false
    fast_mode: true
    times: 6
    g_load: 0.5
    g_wire: 0.5

SAF:
    enable: false
    runtime_en: true
    init_pSA0: 0.05
    init_pSA1: 0.05
    pSA0: 0.0005
    pSA1: 0.0005


phyArrRowSize: 64
phyArrColSize: 64

minConduct: 1e-7
maxConduct: 1e-4

inVBits: 1
inBits: 8
outBits: 12
unitBits: 8
cellBits: 1
has_negative_input: true
max_phy_input_value: 16
max_weight_value: 5
trunc_input: true
dynamic_max_input: true
mode: 0

# area config (μm)
area:
  cell_area: 0.0081       # 4F^2 = 4 * 0.045um ^ 2 =
  share_peripheral: 500
  array_peripheral: 0
  DAC_area: 10.62         # 8 bit DAC, 3096T, T = 3 * F^2
  ADC_area: 2.733750      # 8 bit ADC, 450T
  share_inf_row_size: 64
  share_inf_col_size: 64
  row_share_subarray: 8
  col_share_subarray: 8

print_voltage_conductance: false # print input voltage and cell conductance when computing