# 定点量化参数
[Quantization]
# TensorType: Normal, PN
TensorType = Normal
# RightShiftMode: Abandon, Round, RoundToEvenNearest
RightShiftMode = Round
# WeightUpdateStrategy: StaticRange, DynamicRange
WeightUpdateStrategy = DynamicRange
DataFlowBitWidth = 8
# 神经网络层量化参数
OutputBitWidth = 8
WeightBitWidth = 8
GradOutputBitWidth = 8
ComputeWeightBitWidth = 8
OptimMode = FullFix

# 仿真参数
[Simulator.arch]
Chip_n = 1
Bank_n = 1
Tile_n = 16
PE_n = 16
Crx_n = 16
CrxShape = [512, 512]
OuShape = [128, 128]
CellBits = 2

# 0:Fixed-Point, 4:Simp, 5:TRQ, 6:PimSpec
MMM_Type = 4


