phy_array_readMode: 2
phy_array_writeMode: 0
writeV: 3
readV: 1
computeV: 1
# C2C variation, r = Rtarget * exp(q);  q ~ N(0, theta)   
C2C_en: 
    enable: false
    theta: 0.1
D2D_en: false
# I = k*sinh(a*v)
nonLinearIV_en: false
write_cnt_en: false
energy_cal_en: false
latency_cal:  #all latency is xx ns 
    enable: false
    parMMPhyNum: 256
    parWrPhyNum:  -1
    parPhyWrSize: 64
    phyWrLatency: 2000
    phyMMLatency: 100
    addLatency: 5
    addTreeWideSize: 128
    addTreeSharedNum: 8
    
ir_drop:
    enable: false
    fast_mode: true
    times: 6
    g_load: 0.5
    g_wire: 0.5

SAF:
    enable: true
    runtime_en: true
    init_pSA0: 0.05
    init_pSA1: 0.05
    pSA0: 0.0005
    pSA1: 0.0005

phyArrRowSize: 64
phyArrColSize: 64

minConduct: 1e-7
maxConduct: 1e-4

inVBits: 1
inBits: 12
outBits: 12
unitBits: 12
cellBits: 1
has_negative_input: true
max_phy_input_value: 16
max_weight_value: 4
trunc_input: true
dynamic_max_input: true
mode: 0

# area config (μm)
area:
  F: 0.045
  share_peripheral: 500
  array_peripheral: 0
  DAC_area: 10.62  # 8 bit DAC, 3096T, T = 3 * F^2
  ADC_area: 2.733750   # 8 bit ADC, 450T
  share_inf_row_size: 64
  share_inf_col_size: 64
  row_share_subarray: 8
  col_share_subarray: 8