# 定点量化参数
[Quantization]
# TensorType: Normal, PN
TensorType = Normal
# RightShiftMode: Abandon, Round, RoundToEvenNearest
RightShiftMode = Round
# WeightUpdateStrategy: StaticRange, DynamicRange
WeightUpdateStrategy = DynamicRange
DataFlowBitWidth = 8
# 神经网络层量化参数
OutputBitWidth = 8
WeightBitWidth = 8
GradOutputBitWidth = 8
ComputeWeightBitWidth = 8
OptimMode = FullFix

# 仿真参数
[Simulator.arch]
Chip_n = 1
Bank_n = 1
Tile_n = 16
PE_n = 16
Crx_n = 16
CrxShape = [512, 512]
OuShape = [8, 8]
CellBits = 1

[Simulator.dataPlacement]
DataSplitting = True

[Simulator.staticPerformance]
# PerformanceEvaluateMode: Train, FastModeTrain, Inference, TrainTransientInBuffer
PerformanceEvaluateMode = Inference
Training = True
Epochs = 200
DataSize = 50000
BatchSize = 64
NetMapTimes = [4, 2, 3]
# InputDataShape: [C, H, W]
InputDataShape = [1, 28, 28]
# relu is just a 64bit 2:1 MUX, sign bit is the signal
# staticPerformance para
ActivationUnitNum = 16
# latency para ( #ns )
ActivationUnitLatency = 1
# 0:p&n 1:ref
ArrayMode = 0

[Simulator.staticPerformance.latency]
# ComputeMode: Pipeline or Sequential
ComputeMode = Pipeline

[Simulator.staticPerformance.area]
SingleDACArea = 0.166015625
SingleADCArea = 1200
SingleSHArea = 0.0224609375
SingleCellArea = 0.004096
AdderArea = 0
DAC_n = 4
ADC_n = 4
Adder_n = 1
OR_n = 1
IR_n = 1
SH_n = 4
SA_n = 1

# Wear-Leveling configurations
[Simulator.extension.wearLeveling]
TIWLInterval = 1000
PEShiftInterval = 1000
CrxWlInterval = 1000
CrxWlType = RowColShift
LASRTopK = 0.2
GranularityOfAllocator = PE
GranularityOfTIWL = PE
OverlapUpdate = True
FillingType = Multiple
FillingParam = 2
ShiftNum = 1
StoreTranspose = False
SaveInterval = 15000
SaveDir = /Users/zhouheng/Library/CloudStorage/Dropbox/Codes/pimtorch/onn/wl_output
SaveLiteWlState = True
SaveJsonMapping = False


# 自定义参数，以下所有参数都会导入GlobalCfg，并且值为String，需要自行转换数据类型。
# GlobalCfg中的属性名称与定义相同
[Custom]
# ONN
DataDir = /Users/zhouheng/Datasets
DataName = higgs
JobInfo = Top K
Workers = 1
BatchSize = 1
LR = 0.01
Beta = 0.99
S = 0.2
HiddenLayers = 8
HiddenWidth = 100
FreezeThreshold = -0.1
FeatureSize = 28
Classes = 2
LogInterval = 1000
MaxIters = 10000
UseCUDA = False
GpuID = 0
UseTFboard = False

# Example
BitWidthOfLayers = [16, 16, 16, 16, 16, 16, 16, 16, 16, 16]


